//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SurveyAppEntities : DbContext
    {
        public SurveyAppEntities()
            : base("name=SurveyAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllAnswers> AllAnswers1 { get; set; }
        public virtual DbSet<AnswerSet> AnswerSets { get; set; }
        public virtual DbSet<QuestionSet> QuestionSets { get; set; }
    }
}
